import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using Civic Cycle.",
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1
        className="text-3xl mb-2"
        style={{ fontFamily: "var(--font-display-var), Georgia, serif", fontWeight: 400 }}
      >
        Terms of Service
      </h1>
      <p className="text-sm text-muted-foreground mb-10">Effective May 13, 2026</p>

      <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8 text-sm leading-relaxed">

        <section>
          <h2 className="text-base font-semibold mb-3">1. About Civic Cycle</h2>
          <p>
            Civic Cycle (<strong>civiccycle.org</strong>) is an independent civic technology
            project that collects, summarizes, and delivers information about Fairfax County
            Public Schools School Board and Board of Supervisors meetings. It is operated by
            an individual student developer and is not affiliated with, endorsed by, or
            sponsored by FCPS, the Fairfax County School Board, or Fairfax County Government.
          </p>
          <p className="mt-2">
            By creating an account or using the service you agree to these Terms. If you do
            not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">2. Accounts</h2>
          <p>
            You must provide a valid email address to create an account. You are responsible
            for maintaining the security of your credentials and for all activity that occurs
            under your account. Notify us immediately at{" "}
            <a href="mailto:memeronite@gmail.com" className="underline">memeronite@gmail.com</a>{" "}
            if you suspect unauthorized access.
          </p>
          <p className="mt-2">
            You must be at least 13 years old to use this service. Accounts that appear to
            belong to users under 13 will be removed.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">3. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 mt-2">
            <li>Use the service for any unlawful purpose</li>
            <li>
              Attempt to reverse-engineer, scrape at scale, or systematically extract content
              from the service in a way that burdens our infrastructure
            </li>
            <li>Attempt to gain unauthorized access to any part of the service or its backend</li>
            <li>
              Impersonate another person or misrepresent your affiliation with any organization
            </li>
            <li>Interfere with other users&apos; access to the service</li>
          </ul>
          <p className="mt-3">
            We reserve the right to suspend or terminate accounts that violate these terms
            without prior notice.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">4. Content and Accuracy</h2>
          <p>
            Meeting summaries are generated by an artificial intelligence model (Anthropic
            Claude) from publicly available BoardDocs transcripts. <strong>AI-generated
            summaries may contain errors, omissions, or mischaracterizations.</strong> They
            are provided for convenience and general awareness only.
          </p>
          <p className="mt-2">
            For official, authoritative information about FCPS School Board meetings and
            decisions, always refer to the official BoardDocs records at{" "}
            <a
              href="https://go.boarddocs.com/vsba/fairfax/Board.nsf/Public"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
            >
              go.boarddocs.com/vsba/fairfax/Board.nsf/Public
            </a>{" "}
            and the{" "}
            <a href="https://www.fcps.edu/" target="_blank" rel="noopener noreferrer" className="underline">
              FCPS official website
            </a>.
          </p>
          <p className="mt-2">
            Meeting content sourced from BoardDocs is public government information. We
            reproduce it for informational purposes only. We make no claim of ownership over
            that content.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">5. Email Communications</h2>
          <p>
            By creating an account you are automatically enrolled in the weekly meeting
            digest. You may unsubscribe at any time via the link in any digest email or by
            contacting us. Keyword alert emails are sent only when you have created an alert;
            each email includes a one-click unsubscribe link.
          </p>
          <p className="mt-2">
            We will not send promotional, advertising, or unrelated commercial emails.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">6. Intellectual Property</h2>
          <p>
            The Civic Cycle name, logo, and original code are the property of the operator.
            Meeting transcript content is public government information and is not claimed as
            our property. AI-generated summaries are derivative works of public records; we
            make no proprietary claim over them and do not restrict your right to quote or
            share them with attribution.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">7. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR
            A PARTICULAR PURPOSE, OR ACCURACY. WE DO NOT WARRANT THAT THE SERVICE WILL BE
            UNINTERRUPTED, ERROR-FREE, OR THAT SUMMARIES ARE ACCURATE OR COMPLETE.
          </p>
          <p className="mt-2">
            Civic Cycle is a personal student project with no guaranteed uptime, support
            SLAs, or long-term availability commitment.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">8. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE OPERATOR SHALL NOT BE LIABLE FOR
            ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING
            FROM YOUR USE OF OR INABILITY TO USE THE SERVICE, INCLUDING RELIANCE ON
            AI-GENERATED MEETING SUMMARIES FOR DECISIONS. TOTAL LIABILITY FOR ANY CLAIM
            ARISING FROM USE OF THIS SERVICE SHALL NOT EXCEED FIFTY DOLLARS ($50).
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">9. Termination</h2>
          <p>
            You may stop using the service at any time and request account deletion by
            contacting us. We may suspend or terminate accounts that violate these Terms or
            for any operational reason, with or without notice. We may discontinue the
            service entirely at any time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">10. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the Commonwealth of Virginia, without
            regard to its conflict-of-law provisions. Any dispute arising from these Terms
            or the service shall be resolved in the courts of Fairfax County, Virginia.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">11. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. Material changes will be noted by
            updating the effective date above. Continued use of the service after changes
            constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold mb-3">12. Contact</h2>
          <p>
            <a href="mailto:memeronite@gmail.com" className="underline">memeronite@gmail.com</a>
          </p>
        </section>

      </div>
    </main>
  );
}
